language: ruby
rvm:
- 2.0.0
before_install:
- openssl aes-256-cbc -K $encrypted_c60eefdee1b2_key -iv $encrypted_c60eefdee1b2_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
- cp deploy-key ~/.ssh/id_rsa
script:
- bundle exec rake generate
deploy:
  repo: davidsiaw/davidsiaw.github.io
  email: davidsiaw@gmail.com
  name: David Siaw (via Travis CI)
  local-dir: public
  target-branch: master
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
