language: ruby
rvm:
- 2.0.0
before_install:
- openssl aes-256-cbc -K $encrypted_c60eefdee1b2_key -iv $encrypted_c60eefdee1b2_iv -in deploy-key.enc -out deploy-key -d
- chmod 600 deploy-key
script:
- bundle exec rake generate
- bash deploy
